import React, { useState, useEffect } from 'react';
// import '../../styles/festivalsEvents.css'; // Optional: Custom CSS for additional styling
// import { BsHeart, BsStarFill } from 'react-icons/bs'; // Add this line
import LocationCard from '../LocationCard/LocationCard';
import locations from "../../data/locations.json"
import EventList from '../Events/EventsListingBlock';
import Fuse from "fuse.js";
import toast from 'react-hot-toast';


import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMapMarkerAlt } from "@fortawesome/free-solid-svg-icons";
import eventsEmptyState from '../../assets/images/eventsEmptyState.jpg'; // Adjust the path based on your project structure

// Empty State Component
const EmptyState = () => (
    <div
        style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            textAlign: 'center',
            padding: '40px',
            margin: '20px auto',
            maxWidth: '600px',
        }}
    >
        <img
            src={eventsEmptyState}
            alt="No events available"
            style={{ maxWidth: '100%', height: 'auto', marginBottom: '20px' }}
        />
        <h3>No Events Found</h3>
        <p>
            Please allow location permissions to discover exciting festivals and events near you!
        </p>
        <button
            className="btn btn-black"
            onClick={() => {
                // Optionally, trigger location permission request again
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(
                        () => window.location.reload(),
                        () => toast.error('Location permission is required to fetch events.')
                    );
                }
            }}
        >
            Allow Location
        </button>
    </div>
);
const indianCities = [
    "Aalo",
    "Abohar",
    "Abu Road",
    "Achampet",
    "Acharapakkam",
    "Addanki",
    "Adilabad",
    "Adimali",
    "Adipur",
    "Adoni",
    "Agar Malwa",
    "Agartala",
    "Agiripalli",
    "Agra",
    "Ahilyanagar (Ahmednagar)",
    "Ahmedgarh",
    "Ahore",
    "Aizawl",
    "Ajmer",
    "Akaltara",
    "Akbarpur",
    "Akividu",
    "Akluj",
    "Akola",
    "Akot",
    "Alakode",
    "Alangudi",
    "Alangulam",
    "Alappuzha",
    "Alathur",
    "Alibaug",
    "Aligarh",
    "Alipurduar",
    "Almora",
    "Alsisar (Rajasthan)",
    "Alur",
    "Alwar",
    "Amadalavalasa",
    "Amalapuram",
    "Amalner",
    "Amangal",
    "Amanpur",
    "Amaravathi",
    "Ambajogai",
    "Ambala",
    "Ambikapur",
    "Ambur",
    "Amgaon",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha",
    "Anaikatti",
    "Anakapalle",
    "Anand",
    "Anandapur",
    "Anantapalli",
    "Anantapur",
    "Anaparthi",
    "Anchal",
    "Andaman And Nicobar",
    "Anekal",
    "Angadipuram",
    "Angamaly",
    "Angara",
    "Angul",
    "Anjad",
    "Anjar",
    "Anklav",
    "Ankleshwar",
    "Ankola",
    "Annavaram",
    "Annigeri",
    "Anthiyur",
    "Apra",
    "Arakkonam",
    "Arambagh",
    "Arambol",
    "Aranthangi",
    "Aravakurichi",
    "Ariyalur",
    "Arkalgud",
    "Armoor",
    "Arni",
    "Arsikere",
    "Aruppukottai",
    "Asansol",
    "Ashoknagar",
    "Ashoknagar (West Bengal)",
    "Ashta",
    "Ashta (Maharashtra)",
    "Asika",
    "Aswaraopeta",
    "Athagarh",
    "Athani",
    "Atmakur (Nellore)",
    "Atpadi",
    "Atraulia",
    "Attibele",
    "Attili",
    "Attingal",
    "Attur",
    "Aurangabad (Bihar)",
    "Aurangabad (West Bengal)",
    "Auroville",
    "Aushapur",
    "Avinashi",
    "Ayodhya",
    "Azamgarh",
    "B. Kothakota",
    "Babra",
    "Badami",
    "Badaun",
    "Baddi",
    "Badhra",
    "Badnagar",
    "Badnawar",
    "Badvel",
    "Bagaha",
    "Bagalkot",
    "Bagbahara",
    "Bagepalli",
    "Bagha Purana",
    "Baghmari",
    "Bagnan",
    "Bagru",
    "Bahadurgarh",
    "Bahraich",
    "Baidyabati",
    "Baihar",
    "Baijnath",
    "Baikunthpur",
    "Baindur",
    "Bakhrahat",
    "Balaghat",
    "Balangir",
    "Balasore",
    "Balijipeta",
    "Ballia",
    "Balod",
    "Baloda Bazar",
    "Balotra",
    "Balrampur",
    "Balurghat",
    "Banaganapalli",
    "Banahatti",
    "Banaskantha",
    "Banga",
    "Bangaon",
    "Bangarpet",
    "Bangarupalem",
    "Banki",
    "Bankura",
    "Banswada",
    "Banswara",
    "Bantumilli",
    "Bapatla",
    "Barabanki",
    "Baramati",
    "Baramulla",
    "Baran",
    "Barasat",
    "Baraut",
    "Barbil",
    "Bardoli",
    "Bareilly",
    "Bareja",
    "Bargarh",
    "Barharwa",
    "Barhi",
    "Baripada",
    "Barmer",
    "Barnala",
    "Barpeta Road",
    "Barrackpore",
    "Barshi",
    "Baruipur",
    "Barwadih",
    "Barwaha",
    "Barwani",
    "Basantpur",
    "Basirhat",
    "Basna",
    "Basti",
    "Bathinda",
    "Batlagundu",
    "Bavla",
    "Bayad",
    "Bayana",
    "Bazpur",
    "Beawar",
    "Beed",
    "Beguniapada",
    "Begusarai",
    "Behror",
    "Belagavi (Belgaum)",
    "Belakavadi",
    "Belghoria",
    "Bellampalli",
    "Bellary",
    "Belur",
    "Bemetara",
    "Berachampa",
    "Berhampore (W.B.)",
    "Berhampur (Odisha)",
    "Bestavaripeta",
    "Betalbatim",
    "Betberia",
    "Bethamcherla",
    "Bettiah",
    "Betul",
    "Bhadrachalam",
    "Bhadrak",
    "Bhadravati",
    "Bhagalpur",
    "Bhainsa",
    "Bhandara",
    "Bharamasagara",
    "Bharatpur",
    "Bharuch",
    "Bhatapara",
    "Bhatgaon",
    "Bhatkal",
    "Bhattiprolu",
    "Bhavani",
    "Bhavnagar",
    "Bhawanipatna",
    "Bheemgal",
    "Bhilai",
    "Bhilwara",
    "Bhimadole",
    "Bhimavaram",
    "Bhind",
    "Bhiwadi",
    "Bhiwani",
    "Bhogapuram",
    "Bhongir",
    "Bhopal",
    "Bhubaneswar",
    "Bhuj",
    "Bhuntar",
    "Bhupalpalle",
    "Bhusawal",
    "Bhutan",
    "Bhuvanagiri",
    "Biaora",
    "Bibinagar",
    "Bichkunda",
    "Bidadi",
    "Bidar",
    "Bihar Sharif",
    "Bihpuria",
    "Bijainagar",
    "Bijnor",
    "Bijoynagar",
    "Bikaner",
    "Bikramganj",
    "Bilara",
    "Bilaspur",
    "Bilaspur (Himachal Pradesh)",
    "Bilgi",
    "Bilimora",
    "Billawar",
    "Biraul",
    "Birra",
    "Bishnupur",
    "Bishrampur",
    "Biswanath Chariali",
    "Bobbili",
    "Bodhan",
    "Bodinayakanur",
    "Boisar",
    "Bokaro",
    "Bolpur",
    "Bomdila",
    "Bommidi",
    "Bonakal",
    "Bongaigaon",
    "Bongaon",
    "Borsad",
    "Botad",
    "Brahmapur",
    "Brahmapuri",
    "Brajrajnagar",
    "Buchireddypalem",
    "Budhlada",
    "Buhari",
    "Bulandshahr",
    "Buldana",
    "Bundu",
    "Burdwan",
    "Burhanpur",
    "Burhar",
    "Buttayagudem",
    "Byadagi",
    "Byadgi",
    "Byasanagar",
    "Calicut",
    "Canning",
    "Chagallu",
    "Chakan",
    "Chalakudy",
    "Chalisgaon",
    "Challakere",
    "Challapalli",
    "Chamarajnagar",
    "Chamba",
    "Chamoli",
    "Champa",
    "Champahati",
    "Chanchal",
    "Chandannagar",
    "Chandausi",
    "Chandbali",
    "Chandpur Siau",
    "Chandrakona",
    "Chandrapur",
    "Chandur",
    "Changanassery",
    "Changaramkulam",
    "Channagiri",
    "Channapatna",
    "Channarayapatna",
    "Chanpatia",
    "Chapra",
    "Charkhi Dadri",
    "Chaygaon",
    "Cheeka",
    "Cheepurupalli",
    "Chelpur",
    "Chendrapinni",
    "Chengalpattu",
    "Chengannur",
    "Chennur",
    "Chenthrapini",
    "Cherial",
    "Cherla",
    "Cherpulassery",
    "Cherrapunji",
    "Cherthala",
    "Chetpet",
    "Chevella",
    "Cheyyar",
    "Cheyyur",
    "Chhabra",
    "Chhatarpur",
    "Chhatrapati Sambhajinagar (Aurangabad)",
    "Chhibramau",
    "Chhindwara",
    "Chickmagaluru",
    "Chidambaram",
    "Chikhli",
    "Chikkaballapur",
    "Chikmagalur",
    "Chikodi",
    "Chilakaluripet",
    "Chinnalapatti",
    "Chinnamandem",
    "Chinnamanur",
    "Chinsurah",
    "Chintalapudi",
    "Chintamani",
    "Chinturu",
    "Chiplun",
    "Chiraiyakot",
    "Chirala",
    "Chirawa",
    "Chitradurga",
    "Chittoor",
    "Chittorgarh",
    "Chodavaram",
    "Chon Buri",
    "Chotila",
    "Choutuppal",
    "Churachandpur",
    "Churu",
    "Coimbatore",
    "Colombo",
    "Cooch Behar",
    "Coonoor",
    "Cuddalore",
    "Cumbum",
    "Cumbum (AP)",
    "Cuttack",
    "Dabra",
    "Dahanu",
    "Dahegam",
    "Dahod",
    "Dakshin Barasat",
    "Dalli Rajhara",
    "Dalmianagar",
    "Daman",
    "Damarcherla",
    "Dammapeta",
    "Damoh",
    "Danapur",
    "Dandeli",
    "Dang",
    "Dankaur",
    "Dantewada",
    "Daporijo",
    "Darbhanga",
    "Darjeeling",
    "Darlapudi",
    "Darsi",
    "Darwha",
    "Dasuya",
    "Datia",
    "Daund",
    "Dausa",
    "Davanagere",
    "Davuluru",
    "Deesa",
    "Dehradun",
    "Deogadh",
    "Deoghar",
    "Deoli",
    "Deoli (Rajasthan)",
    "Deoli(Rajasthan)",
    "Deoria",
    "Deralakatte",
    "Devadurga",
    "Devakottai",
    "Devarakadra",
    "Devarakonda",
    "Devarapalle",
    "Devarapalli",
    "Devgad",
    "Dewas",
    "Dhamnod",
    "Dhampur",
    "Dhamtari",
    "Dhanaura",
    "Dhanbad",
    "Dhanera",
    "Dhar",
    "Dharamjaigarh",
    "Dharampur",
    "Dharamsala",
    "Dharamshala",
    "Dharapuram",
    "Dharashiv (Osmanabad)",
    "Dharmanagar",
    "Dharmapuri",
    "Dharmavaram",
    "Dharpally",
    "Dharpur",
    "Dharuhera",
    "Dharwad",
    "Dhaulana",
    "Dhekiajuli",
    "Dhemaji",
    "Dhenkanal",
    "Dholka",
    "Dholpur",
    "Dhone",
    "Dhoraji",
    "Dhrangadhra",
    "Dhubri",
    "Dhule",
    "Dhulian",
    "Dhuliyan",
    "Dhuri",
    "Diamond Harbour",
    "Dibrugarh",
    "Digras",
    "Dildar Nagar",
    "Dima Hasao",
    "Dimapur",
    "Dinanagar",
    "Dindigul",
    "Diphu",
    "Dirang",
    "Doddaballapura",
    "Doimukh",
    "Domkal",
    "Dongargarh",
    "Doolahat Bazar",
    "Doraha",
    "Dornakal",
    "Dowlaiswaram",
    "Draksharamam",
    "Dubbaka",
    "Dubrajpur",
    "Dudhi",
    "Dumka",
    "Dungarpur",
    "Durg",
    "Durgapur",
    "Dwarka",
    "East Godavari",
    "Edappal",
    "Edlapadu",
    "Ekma",
    "Elesvaram",
    "Eluru",
    "Enkoor",
    "Eramalloor",
    "Erandol",
    "Erattupetta",
    "Ernakulam",
    "Erode",
    "Etah",
    "Etawah",
    "Ettumanoor",
    "Eturnagaram",
    "Faizabad",
    "Falakata",
    "Falna",
    "Faridkot",
    "Farrukhabad",
    "Fatehabad",
    "Fatehgarh Sahib",
    "Fatehpur",
    "Fatehpur(Rajasthan)",
    "Fazilka",
    "Firozabad",
    "Firozpur",
    "Forbesganj",
    "France",
    "Fulkusma",
    "G.Mamidada",
    "Gadag",
    "Gadarwara",
    "Gadchiroli",
    "Gadwal",
    "Gajapathinagaram",
    "Gajendragarh",
    "Gajwel",
    "Gampalagudem",
    "Ganapavaram",
    "Gandhidham",
    "Gandhinagar",
    "Gangarampur",
    "Gangavati",
    "Gangoh",
    "Gangtok",
    "Ganjam",
    "Ganjbasoda",
    "Gannavaram",
    "Garhwal",
    "Garla",
    "Gauribidanur",
    "Gauriganj",
    "Gaya",
    "Gazole",
    "Georai",
    "Ghatanji",
    "Ghazipur",
    "Ghorasahan",
    "Ghumarwin",
    "Giddalur",
    "Gingee",
    "Giridih",
    "Goa",
    "Goalpara",
    "Gobichettipalayam",
    "Godavarikhani",
    "Godda",
    "Godhra",
    "Gogawa",
    "Gohana",
    "Gokak",
    "Gokarna",
    "Gokavaram",
    "Gola Bazar",
    "Golaghat",
    "Gollaprolu",
    "Gonda",
    "Gondal",
    "Gondia",
    "Goolikkadavu",
    "Gooty",
    "Gopalganj",
    "Gopalpet",
    "Gopiganj",
    "Gorakhpur",
    "Goramadagu",
    "Gorantla",
    "Gotegaon",
    "Gownipalli",
    "Gudivada",
    "Gudiyatham",
    "Gudlavalleru",
    "Gudur",
    "Guhagar",
    "Gulaothi",
    "Guledgudda",
    "Gummadidala",
    "Guna",
    "Gundlupet",
    "Guntakal",
    "Guntur",
    "Gurap",
    "Gurazala",
    "Gurdaspur",
    "Guruvayur",
    "Guwahati",
    "Gwalior",
    "Habra",
    "Haflong",
    "Hagaribommanahalli",
    "Hajipur",
    "Haldia",
    "Halduchaur",
    "Haldwani",
    "Haliya",
    "Halol",
    "Hamirpur (HP)",
    "Hampi",
    "Handwara",
    "Hanuman Junction",
    "Hanumangarh",
    "Hapur",
    "Harda",
    "Hardoi",
    "Haria",
    "Haridwar",
    "Harihar",
    "Haripad",
    "Harugeri",
    "Harur",
    "Hasanparthy",
    "Hasanparthy",
    "Hasanpur",
    "Hasnabad",
    "Hassan",
    "Hathras",
    "Haveri",
    "Hazaribagh",
    "Himmatnagar",
    "Hindaun City",
    "Hindupur",
    "Hinganghat",
    "Hingoli",
    "Hiramandalam",
    "Hirekerur",
    "Hiriyur",
    "Hisar",
    "Holenarasipura",
    "Honnali",
    "Honnavara",
    "Hooghly",
    "Hoshangabad",
    "Hoshiarpur",
    "Hoskote",
    "Hospet",
    "Hosur",
    "Howrah",
    "Hubballi (Hubli)",
    "Hunagunda",
    "Hunsur",
    "Husnabad",
    "Huvinahadagali",
    "Huzurabad",
    "Huzurnagar",
    "Ichalkaranji",
    "Ichchapuram",
    "Idappadi",
    "Idar",
    "Idukki",
    "Ieeja",
    "Imphal",
    "Indapur",
    "Indi",
    "Indore",
    "Indukurpeta",
    "Irinjalakuda",
    "Itanagar",
    "Itarsi",
    "Jabalpur",
    "Jadcherla",
    "Jagalur",
    "Jagatdal",
    "Jagdalpur",
    "Jaggampeta",
    "Jaggayyapeta",
    "Jagraon",
    "Jagtial",
    "Jaipur",
    "Jaisalmer",
    "Jajpur Road",
    "Jajpur Town (Odisha)",
    "Jalakandapuram",
    "Jalalabad",
    "Jalandhar",
    "Jalaun",
    "Jalgaon",
    "Jalna",
    "Jalore",
    "Jalpaiguri",
    "Jami",
    "Jamkhandi",
    "Jamkhed",
    "Jammalamadugu",
    "Jammikunta",
    "Jammu",
    "Jamnagar",
    "Jamner",
    "Jamshedpur",
    "Jamui",
    "Jangaon",
    "Jangareddy Gudem",
    "Janjgir",
    "Jaora",
    "Jasdan",
    "Jashpur",
    "Jatni",
    "Jaunpur",
    "Jayamkondacholapuram",
    "Jaysingpur",
    "Jehanabad",
    "Jejuri",
    "Jetpur",
    "Jewar",
    "Jeypore",
    "Jhabua",
    "Jhajha",
    "Jhajjar",
    "Jhansi",
    "Jhargram",
    "Jharsuguda",
    "Jhunjhunu",
    "Jiaganj",
    "Jigani",
    "Jind",
    "Jintur",
    "Jirapur",
    "Jodhpur",
    "Jolarpettai",
    "Jorhat",
    "Joynagar Majilpur",
    "Junagadh",
    "Junagarh",
    "K.D Peta",
    "Kadakkal",
    "Kadapa",
    "Kadi",
    "Kadiri",
    "Kadiyam",
    "Kadthal",
    "Kaikaluru",
    "Kaithal",
    "Kakarapalli",
    "Kakinada",
    "Kalaburagi (Gulbarga)",
    "Kalady",
    "Kalanaur",
    "Kalimpong",
    "Kalla",
    "Kallachi",
    "Kalladikode",
    "Kallakurichi",
    "Kallur",
    "Kalluru",
    "Kalna",
    "Kalol (Gandhinagar)",
    "Kalol (Panchmahal)",
    "Kalwakurthy",
    "Kalyani",
    "Kamalaapur",
    "Kamalapur",
    "Kamanaickenpalayam",
    "Kamareddy",
    "Kamavarapukota",
    "Kambainallur",
    "Kamptee",
    "Kamrej",
    "Kanakapura",
    "Kanatal",
    "Kanchikacherla",
    "Kanchipuram",
    "Kandamangalam",
    "Kandukur",
    "Kangayam",
    "Kangra",
    "Kanhangad",
    "Kanichar",
    "Kanigiri",
    "Kanipakam",
    "Kanjirappally",
    "Kankavli",
    "Kanker",
    "Kankipadu",
    "Kankroli",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kantabanji",
    "Kanyakumari",
    "Kapadvanj",
    "Kapurthala",
    "Karad",
    "Karaikal",
    "Karambakkudi",
    "Karanja Lad",
    "Karanjia",
    "Kareli",
    "Karepalli",
    "Kargi Road",
    "Karimangalam",
    "Karimganj",
    "Karimnagar",
    "Kariyad",
    "Karjat",
    "Karkala",
    "Karmala",
    "Karmamthody",
    "Karnal",
    "Karunagapally",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kasdol",
    "Kasganj",
    "Kashig",
    "Kashipur",
    "Kashti",
    "Kasibugga",
    "Katghora",
    "Kathipudi",
    "Kathmandu",
    "Kathua",
    "Katihar",
    "Katni",
    "Katra",
    "Katrenikona",
    "Kattappana",
    "Katwa",
    "Kavali",
    "Kaveripattinam",
    "Kaviti",
    "Kawardha",
    "Kayamkulam",
    "Kazhakkoottam",
    "Kazipet",
    "Kekri",
    "Kendrapara",
    "Keonjhar",
    "Kesamudram",
    "Kesinga",
    "Kevadia",
    "Khachrod",
    "Khadda",
    "Khajani",
    "Khajipet",
    "Khajuraho",
    "Khalilabad",
    "Khambhat",
    "Khamgaon",
    "Khammam",
    "Khanapur",
    "Khandela",
    "Khandwa",
    "Khanna",
    "Kharagpur",
    "Kharghar",
    "Khargone",
    "Khariar Road",
    "Kharsia",
    "Khategaon",
    "Khatima",
    "Khatta",
    "Khed",
    "Kheda",
    "Khedbrahma",
    "Khila",
    "Khopoli",
    "Khowai",
    "Khurja",
    "Kichha",
    "Kim",
    "Kinathukadavu",
    "Kinnaur",
    "Kirlampudi",
    "Kishanganj",
    "Kishangarh",
    "Kodad",
    "Kodagu (Coorg)",
    "Kodaikanal",
    "Kodakara",
    "Kodaly",
    "Koderma",
    "Kodumur",
    "Kodumuru",
    "Kodungallur",
    "Kohima",
    "Koilkuntla",
    "Kokrajhar",
    "Kolar",
    "Kolhapur",
    "Kollam",
    "Kollapur",
    "Kollengode",
    "Komarapalayam",
    "Kondagaon",
    "Kondlahalli",
    "Konithiwada",
    "Konni",
    "Koothattukulam",
    "Kopargaon",
    "Koppam",
    "Koraput",
    "Koratagere",
    "Korba",
    "Korutla",
    "Korwa",
    "Kosamba",
    "Kosgi",
    "Kota",
    "Kota (AP)",
    "Kotabommali",
    "Kotananduru",
    "Kotdwara",
    "Kothacheruvu",
    "Kothagudem",
    "Kothakota",
    "Kothamangalam",
    "Kothapalli",
    "Kothapeta",
    "Kothavalasa",
    "Kotkapura",
    "Kotma",
    "Kotpad",
    "Kotputli",
    "Kottayam",
    "Kottayi",
    "Kottiyam",
    "Kotturu",
    "Kovilpatti",
    "Kovur (Nellore)",
    "Kovvur",
    "Koyyalagudem",
    "Kozhikode",
    "Kozhinjampara",
    "Krishnagiri",
    "Krishnanagar",
    "Krishnarajanagara",
    "Krishnarajpete (K.R.Pete)",
    "Krosuru",
    "Kruthivennu",
    "Kuchaman City",
    "Kuchipudi",
    "Kudus",
    "Kujang",
    "Kukshi",
    "Kulithalai",
    "Kullu",
    "Kumarakom",
    "Kumbakonam",
    "Kumily",
    "Kunda",
    "Kundapura",
    "Kunigal",
    "Kunkuri",
    "Kunnamkulam",
    "Kuravilangad",
    "Kurnool",
    "Kurseong",
    "Kurud",
    "Kurukshetra",
    "Kurumaseri",
    "Kurundwad",
    "Kushalnagar",
    "Kushinagar",
    "Kusumgram",
    "Kutch",
    "Kuthuparamba",
    "Ladakh",
    "Lakhanpur",
    "Lakhimpur",
    "Lakhimpur Kheri",
    "Lakhisarai",
    "Lakkavaram",
    "Lakshmeshwara",
    "Lakshmikantapur",
    "Lalgudi",
    "Lalitpur",
    "Lansdowne",
    "Latur",
    "Lavasa",
    "Leeja",
    "Leh",
    "Lingasugur",
    "Lohardaga",
    "Lonand",
    "Lonar",
    "Lonavala",
    "Loni",
    "Lucknow",
    "Ludhiana",
    "Lunawada",
    "Luxettipet",
    "MUNNAR",
    "Macherla",
    "Machilipatnam",
    "Madalu",
    "Madanapalle",
    "Maddur",
    "Madhavaram",
    "Madhepura",
    "Madhira",
    "Madikeri",
    "Madugula",
    "Madurai",
    "Magadi",
    "Mahabaleshwar",
    "Mahabubabad",
    "Mahad",
    "Mahalingpur",
    "Maharajganj",
    "Mahasamund",
    "Mahbubnagar",
    "Mahemdavad",
    "Maheshtala",
    "Maheshwar",
    "Maheshwaram",
    "Mahishadal",
    "Mahudha",
    "Mahuva",
    "Makrana",
    "Makthal",
    "Malappuram",
    "Malda",
    "Malebennur",
    "Malegaon",
    "Malerkotla",
    "Malikipuram",
    "Malkangiri",
    "Malkapur",
    "Mall",
    "Malout",
    "Malur",
    "Mamallapuram",
    "Manali",
    "Manamadurai",
    "Mananthavady",
    "Manapparai",
    "Manawar",
    "Mancherial",
    "Mandapeta",
    "Mandarmoni",
    "Mandasa",
    "Mandav",
    "Mandawa",
    "Mandi",
    "Mandi Dabwali",
    "Mandi Gobindgarh",
    "Mandla",
    "Mandsaur",
    "Mandvi",
    "Mandwa",
    "Mandya",
    "Manendragarh",
    "Mangalagiri",
    "Mangaldoi",
    "Mangaluru (Mangalore)",
    "Mangar",
    "Manikonda (AP)",
    "Manipal",
    "Manjeri",
    "Manmad",
    "Mannargudi",
    "Mannarkkad",
    "Mannur",
    "Mansa",
    "Manthani",
    "Manuguru",
    "Manvi",
    "Maraimalai Nagar",
    "Marayur",
    "Margao",
    "Margherita",
    "Markapur",
    "Marpalle",
    "Marripeda",
    "Marthandam",
    "Martur",
    "Maslandapur",
    "Math Chandipur",
    "Mathabhanga",
    "Mathura",
    "Mattannur",
    "Mau",
    "Mavelikkara",
    "Mayannur",
    "Mayiladuthurai",
    "Medak",
    "Medarametla",
    "Medchal",
    "Medininagar",
    "Meerut",
    "Mehkar",
    "Mehsana",
    "Melattur",
    "Melli",
    "Memari",
    "Metpally",
    "Mettuppalayam",
    "Mettur",
    "Mhow",
    "Midnapore",
    "Miraj",
    "Mirganj",
    "Miryalaguda",
    "Mirzapur",
    "Moga",
    "Mohali",
    "Mokama",
    "Molakalmuru",
    "Mominpet",
    "Moodbidri",
    "Moradabad",
    "Moranhat",
    "Morbi",
    "Morena",
    "Morigaon",
    "Morinda",
    "Mothkur",
    "Motihari",
    "Moyna",
    "Mudalagi",
    "Muddebihal",
    "Mudhol",
    "Mudigere",
    "Mughalsarai",
    "Mukerian",
    "Mukkam",
    "Muktsar",
    "Mulbagal",
    "Mulkanoor",
    "Mullanpur",
    "Mulleria",
    "Mulugu",
    "Mulugu Ghanpur",
    "Mummidivaram",
    "Mundakayam",
    "Mundargi",
    "Mundra",
    "Mungra Badshahpur",
    "Muniguda",
    "Muradnagar",
    "Murshidabad",
    "Murtizapur",
    "Musiri",
    "Mussoorie",
    "Muvattupuzha",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mydukur",
    "Mylavaram",
    "Mysuru (Mysore)",
    "Nabadwip",
    "Nabarangpur",
    "Nabha",
    "Nadia",
    "Nadiad",
    "Nagamangala",
    "Nagaon",
    "Nagapattinam",
    "Nagari",
    "Nagarkurnool",
    "Nagaur",
    "Nagayalanka",
    "Nagda",
    "Nagercoil",
    "Nagothane",
    "Nagpur",
    "Naharlagun",
    "Naidupeta",
    "Naihati",
    "Nainital",
    "Najafgarh",
    "Najibabad",
    "Nakhatrana",
    "Nakodar",
    "Nakrekal",
    "Nalbari",
    "Nalgonda",
    "Nallajerla",
    "Namakkal",
    "Namchi",
    "Namkhana",
    "Namsai",
    "Nandakumar",
    "Nanded",
    "Nandigama",
    "Nandikotkur",
    "Nandipet",
    "Nandurbar",
    "Nandyal",
    "Nanjanagudu",
    "Nanpara",
    "Narasannapeta",
    "Narayankhed",
    "Narayanpet",
    "Narayanpur",
    "Narayanpur (Assam)",
    "Narayanpur (CH)",
    "Nargund",
    "Narnaul",
    "Narsampet",
    "Narsapur",
    "Narsapur (Medak)",
    "Narsinghpur",
    "Narsipatnam",
    "Narwana",
    "Nashik",
    "Natham",
    "Nathdwara",
    "Nautanwa",
    "Navsari",
    "Nawada",
    "Nawalgarh",
    "Nawanshahr",
    "Nawapara",
    "Nayagarh",
    "Nazira",
    "Nazirpur",
    "Nedumbassery",
    "Nedumkandam",
    "Neelapalli",
    "Neemrana",
    "Neemuch",
    "Nelakondapalli",
    "Nelamangala",
    "Nellimarla",
    "Nellimoodu",
    "Nellore",
    "Nemmara",
    "Nenmara",
    "Nepalgunj",
    "Ner Parsopant",
    "Neral",
    "Nereducharla",
    "New Tehri",
    "Neyveli",
    "Nichlaul",
    "Nidadavolu",
    "Nilagiri",
    "Nilakottai",
    "Nilanga",
    "Nimapara",
    "Nimbahera",
    "Nindra",
    "Nipani",
    "Niphad",
    "Nirjuli",
    "Nizamabad",
    "Nokha",
    "Nooranad",
    "Nurpur",
    "Nuzvid",
    "Nyamathi",
    "Oddanchatram",
    "Ojhar",
    "Okha",
    "Ongole",
    "Ooty",
    "Orai",
    "Orchha",
    "Ottapalam",
    "P. Dharmavaram",
    "P.Gannavaram",
    "Padampur",
    "Padrauna",
    "Padubidri",
    "Pakala",
    "Pala",
    "Palakkad",
    "Palakollu",
    "Palakonda",
    "Palakurthy",
    "Palamaner",
    "Palampur",
    "Palani",
    "Palanpur",
    "Palapetty",
    "Palasa",
    "Palghar",
    "Pali",
    "Palia Kalan",
    "Palitana",
    "Palladam",
    "Pallickathodu",
    "Pallipalayam",
    "Palluruthy",
    "Palwal",
    "Palwancha",
    "Pamarru",
    "Pamidi",
    "Pamuru",
    "Panachamoodu",
    "Panaji",
    "Panapakkam",
    "Panchgani",
    "Panchkula",
    "Pandalam",
    "Pandavapura",
    "Pandhana",
    "Pandharkawada",
    "Pandharpur",
    "Pandua",
    "Panipat",
    "Panna",
    "Panruti",
    "Pansemal",
    "Paonta Sahib",
    "Papanasam",
    "Paradeep",
    "Paralakhemundi",
    "Parappanangadi",
    "Paratwada",
    "Parbhani",
    "Parchur",
    "Parigi (Telangana)",
    "Parkal",
    "Parli",
    "Parvathipuram",
    "Parwanoo",
    "Pasighat",
    "Patan",
    "Patan (CG)",
    "Patan (Satara)",
    "Pathalgaon",
    "Pathanamthitta",
    "Pathanapuram",
    "Pathankot",
    "Pathapatnam",
    "Pathsala",
    "Patiala",
    "Patna",
    "Patran",
    "Patratu",
    "Pattambi",
    "Pattukkottai",
    "Pavagada",
    "Payakaraopeta",
    "Payyanur",
    "Payyoli",
    "Pazhayannur",
    "Pebbair",
    "Pedana",
    "Pedanandipadu",
    "Pedapadu",
    "Peddapalli",
    "Peddapuram",
    "Pen",
    "Pendra",
    "Pennagaram",
    "Penuganchiprolu",
    "Penugonda",
    "Peralam",
    "Perambalur",
    "Peravoor",
    "Peringamala",
    "Peringottukurissi",
    "Perinthalmanna",
    "Periyapatna",
    "Pernambut",
    "Perundurai",
    "Petlad",
    "Phagwara",
    "Phalodi",
    "Phaltan",
    "Phulbani",
    "Piduguralla",
    "Pilani",
    "Pileru",
    "Pilibhit",
    "Pimpalner",
    "Pimpri",
    "Pinjore",
    "Pipariya",
    "Pipraich",
    "Pithampur",
    "Pithapuram",
    "Pithora",
    "Pithoragarh",
    "Pitlam",
    "Pochampally",
    "Podalakur",
    "Podili",
    "Polavaram",
    "Pollachi",
    "Pondicherry",
    "Ponduru",
    "Ponkunnam",
    "Ponnamaravathi",
    "Ponnani",
    "Ponneri",
    "Poovar",
    "Porbandar",
    "Port Blair",
    "Porumamilla",
    "Pratapgarh (Rajasthan)",
    "Pratapgarh (UP)",
    "Prayagraj (Allahabad)",
    "Proddatur",
    "Pudukkottai",
    "Pulgaon",
    "Puliampatti",
    "Pulivendula",
    "Puliyangudi",
    "Pulluvila",
    "Pulpally",
    "Pulwama",
    "Punalur",
    "Punganur",
    "Puri",
    "Purnea",
    "Purulia",
    "Pusad",
    "Pusapatirega",
    "Pushkar",
    "Puthenvelikara",
    "Puthenvelikkara",
    "Puthoor",
    "Puttur (Andhra Pradesh)",
    "Puttur (Karnataka)",
    "Rabkavi Banhatti",
    "Radhamoni",
    "Raebareli",
    "Raghopur",
    "Raghunathganj",
    "Rahata",
    "Rahimatpur",
    "Rahuri",
    "Raibag",
    "Raichur",
    "Raigad",
    "Raiganj",
    "Raigarh",
    "Raikal",
    "Raikot",
    "Railway Koduru",
    "Raipur",
    "Raipuriya",
    "Raisinghnagar",
    "Raja Ka Bagh",
    "Rajakumari",
    "Rajam",
    "Rajamahendravaram (Rajahmundry)",
    "Rajapalayam",
    "Rajapur",
    "Rajarampalli",
    "Rajavommangi",
    "Rajgangpur",
    "Rajgurunagar",
    "Rajiana",
    "Rajkot",
    "Rajnandgaon",
    "Rajpipla",
    "Rajpur",
    "Rajpura",
    "Rajsamand",
    "Rajula",
    "Ramachandrapuram",
    "Ramanagara",
    "Ramanathapuram",
    "Ramayampet",
    "Ramdurg",
    "Rameswarpur",
    "Ramgarh",
    "Ramgarhwa",
    "Ramjibanpur",
    "Ramnagar",
    "Rampachodavaram",
    "Rampur",
    "Ramtek",
    "Ranaghat",
    "Ranastalam",
    "Ranchi",
    "Ranebennur",
    "Rangia",
    "Raniganj",
    "Ranipet",
    "Ranni",
    "Rapur",
    "Rasipuram",
    "Rath",
    "Ratlam",
    "Ratnagiri",
    "Ratnagiri (Odisha)",
    "Ravulapalem",
    "Raxaul",
    "Rayachoti",
    "Rayagada",
    "Rayavaram",
    "Razole",
    "Rentachintala",
    "Renukoot",
    "Repalle",
    "Revdanda",
    "Rewa",
    "Rewari",
    "RiBhoi",
    "Ringas",
    "Rishikesh",
    "Rishra",
    "Robertsganj",
    "Rohtak",
    "Ron",
    "Rongjeng",
    "Roorkee",
    "Rourkela",
    "Routhulapudi",
    "Rudauli",
    "Rudrapur",
    "Rupnagar",
    "Sabbavaram",
    "Sadasivpet",
    "Safidon",
    "Sagar",
    "Sagwara",
    "Saharanpur",
    "Saharsa",
    "Sahjanwa",
    "Sakleshpur",
    "Sakti",
    "Salem",
    "Saligrama",
    "Salihundam",
    "Salur",
    "Samalkota",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Sambhar",
    "Samsi",
    "Sanand",
    "Sanawad",
    "Sangamner",
    "Sangareddy",
    "Sangaria",
    "Sangli",
    "Sangola",
    "Sangrur",
    "Sankarankoil",
    "Sankarapuram",
    "Sankeshwar",
    "Sankri",
    "Santhebennur",
    "Sanwer",
    "Saoner",
    "Saraipali",
    "Sarangarh",
    "Sarangpur",
    "Sarapaka",
    "Sardhana",
    "Sardulgarh",
    "Sarnath",
    "Sarni",
    "Sarsiwa",
    "Sasaram",
    "Satana",
    "Satara",
    "Sathankulam",
    "Sathupally",
    "Sathyamangalam",
    "Satmile",
    "Satna",
    "Sattenapalle",
    "Saundatti",
    "Sawai Madhopur",
    "Sawantwadi",
    "Sayan",
    "Secunderabad",
    "Seethanagaram",
    "Sehmalpur",
    "Sehore",
    "Selu",
    "Semiliguda",
    "Senapati",
    "Sendhwa",
    "Sendurai",
    "Sengottai",
    "Seoni",
    "Seoni Malwa",
    "Serampore",
    "Shadnagar",
    "Shahada",
    "Shahapur",
    "Shahdol",
    "Shahjahanpur",
    "Shahpur",
    "Shahpura",
    "Shajapur",
    "Shamgarh",
    "Shankarampet",
    "Shankarpally",
    "Shankarpur",
    "Shela",
    "Sheopur",
    "Sheorinarayan",
    "Shikaripur",
    "Shikarpur",
    "Shikrapur",
    "Shillong",
    "Shimla",
    "Shindkheda",
    "Shirahatti",
    "Shirali",
    "Shirpur",
    "Shirur",
    "Shivamogga",
    "Shivpuri",
    "Shopian",
    "Shoranur",
    "Shrigonda",
    "Shrirampur",
    "Shujalpur",
    "Shuklaganj",
    "Siddharthnagar",
    "Siddhpur",
    "Siddipet",
    "Sidlaghatta",
    "Sihora",
    "Sikar",
    "Silchar",
    "Siliguri",
    "Silvassa",
    "Sindhanur",
    "Sindhudurg",
    "Singapore",
    "Singarayakonda",
    "Singrauli",
    "Sinnar",
    "Sira",
    "Sircilla",
    "Sirmaur",
    "Sirohi",
    "Sirsa",
    "Sirsi",
    "Siruguppa",
    "Sitamarhi",
    "Sitapur",
    "Sivaganga",
    "Sivakasi",
    "Sivasagar",
    "Siwan",
    "Solan",
    "Solapur",
    "Solukhumbu",
    "Sompeta",
    "Sonari",
    "Songadh",
    "Sonipat",
    "Sonkatch",
    "Soron",
    "South 24 Parganas",
    "Sri Ganganagar",
    "Sri Sathya Sai",
    "Srikakulam",
    "Srinagar",
    "Srirangapatna",
    "Srivaikuntam",
    "Srivilliputhur",
    "Station Ghanpur",
    "Sugauli",
    "Sujangarh",
    "Sukma",
    "Sultanabad",
    "Sultanpur",
    "Sulthan Bathery",
    "Sumerpur",
    "Sundar Nagar",
    "Sundargarh",
    "Supaul",
    "Surajpur",
    "Surat",
    "Surathkal",
    "Surendranagar",
    "Suri",
    "Suryapet",
    "T.Narasapuram",
    "Tadepalligudem",
    "Tadikalapudi",
    "Tadipatri",
    "Talcher",
    "Taliparamba",
    "Tallapudi",
    "Tallarevu",
    "Talwandi Bhai",
    "Tamluk",
    "Tanda",
    "Tandur",
    "Tangla",
    "Tangutur",
    "Tanuku",
    "Tarapur",
    "Tarikere",
    "Tasgaon",
    "Tatipaka",
    "Tawang",
    "Tekkali",
    "Tembhurni",
    "Tenali",
    "Tenkasi",
    "Terdal",
    "Tezpur",
    "Tezu",
    "Thalassery",
    "Thalayolaparambu",
    "Thalikulam",
    "Thallada",
    "Thamarassery",
    "Thanipadi",
    "Thanjavur",
    "Tharad",
    "Theni",
    "Thimmapuram (Addu Road)",
    "Thirubuvanai",
    "Thirumalagiri",
    "Thiruthuraipoondi",
    "Thiruttani",
    "Thiruvalla",
    "Thiruvarur",
    "Thodupuzha",
    "Thoothukudi",
    "Thorrur",
    "Thottiyam",
    "Thriprayar",
    "Thrissur",
    "Thullur",
    "Thuraiyur",
    "Tilda Neora",
    "Tindivanam",
    "Tinsukia",
    "Tiptur",
    "Tiruchendur",
    "Tirukoilur",
    "Tirumakudalu Narasipura",
    "Tirunelveli",
    "Tirupati",
    "Tirupattur",
    "Tirupur",
    "Tirur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Tiruvuru",
    "Titagarh",
    "Titlagarh",
    "Tittakudi",
    "Tonk",
    "Toopran",
    "Trichy",
    "Trivandrum",
    "Tumakuru (Tumkur)",
    "Tumsar",
    "Tura",
    "Turputallu",
    "Turuvekere",
    "Udaipur",
    "Udaynarayanpur",
    "Udgir",
    "Udhampur",
    "Udumalpet",
    "Udupi",
    "Ujhani",
    "Ujjain",
    "Ulikkal",
    "Uluberia",
    "Ulundurpet",
    "Umaria",
    "Umbergaon",
    "Umbraj",
    "Umerkote",
    "Umred",
    "Una",
    "Una (Gujarat)",
    "Undavalli",
    "Unnao",
    "Uppada",
    "Uthamapalayam",
    "Uthangarai",
    "Uthiramerur",
    "Uthukottai",
    "Utraula",
    "Uttara Kannada",
    "Uttarkashi",
    "Vadakara",
    "Vadakkencherry",
    "Vadalur",
    "Vadanappally",
    "Vadodara",
    "Vaduj",
    "Vaijapur",
    "Valaparla",
    "Valigonda",
    "Valluru",
    "Valsad",
    "Vaniyambadi",
    "Vapi",
    "Varadaiahpalem",
    "Varadiyam",
    "Varanasi",
    "Varkala",
    "Vasind",
    "Vatsavai",
    "Vazhapadi",
    "Vedasandur",
    "Veeraghattam",
    "Velangi",
    "Velanja",
    "Velanthavalam",
    "Vellakoil",
    "Vellampalli",
    "Vellore",
    "Velugodu",
    "Vempalli",
    "Vemulawada",
    "Vengurla",
    "Venkatapuram",
    "Veraval",
    "Vetapalem",
    "Vettaikaranpudur",
    "Vettavalam",
    "Vidisha",
    "Vijapur",
    "Vijayapura (Bengaluru Rural)",
    "Vijayapura (Bijapur)",
    "Vijayarai",
    "Vijayawada",
    "Vikarabad",
    "Vikasnagar",
    "Vikravandi",
    "Villupuram",
    "Vinukonda",
    "Viralimalai",
    "Virudhachalam",
    "Virudhunagar",
    "Visnagar",
    "Vissannapeta",
    "Vita",
    "Vithlapur",
    "Vizag (Visakhapatnam)",
    "Vizianagaram",
    "Vrindavan",
    "Vuyyuru",
    "Vyara",
    "Wadakkancherry",
    "Wai",
    "Waluj",
    "Wanaparthy",
    "Wani",
    "Warangal",
    "Wardha",
    "Warora",
    "Washim",
    "Wayanad",
    "West Kameng",
    "Wyra",
    "Yadagirigutta",
    "Yamunanagar",
    "Yanam",
    "Yangon",
    "Yavatmal",
    "Yelagiri",
    "Yelburga",
    "Yeleswaram",
    "Yellamanchili",
    "Yellandu",
    "Yellareddy",
    "Yellareddypet",
    "Yemmiganur",
    "Yeola",
    "Yerragondapalem",
    "Yerraguntla",
    "Yewat",
    "Yuksom",
    "Zaheerabad",
    "Zarap",
    "Ziro",
    "Mumbai",
    "Delhi-NCR",
    "Bengaluru",
    "Hyderabad",
    "Chandigarh",
    "Ahmedabad",
    "Chennai",
    "Pune",
    "Kolkata",
    "Kochi"
];

// const Insider.inknownCities = [
//     {
//         "name": "Ahmedabad",
//         "slug": "homescreen-ahmedabad",
//         "geolocation": {
//             "lat": 23.0225,
//             "lng": 72.5714
//         },
//         "_id": "5698d734d393d291630ca65a",
//         "pinned": false
//     },
//     {
//         "name": "Alibaug",
//         "slug": "homescreen-alibaug",
//         "geolocation": {
//             "lat": 18.658,
//             "lng": 72.863
//         },
//         "_id": "614ad4ccb77c194ee10fac86",
//         "pinned": false
//     },
//     {
//         "name": "Alwar",
//         "slug": "homescreen-alwar",
//         "geolocation": {
//             "lat": 27.5546242,
//             "lng": 76.5763355
//         },
//         "_id": "5bf3e5a7b4d0950cd417a73a",
//         "pinned": false
//     },
//     {
//         "name": "Amritsar",
//         "slug": "homescreen-amritsar",
//         "geolocation": {
//             "lat": 31.634,
//             "lng": 74.8723
//         },
//         "_id": "5926cbea323c42f0b3612323",
//         "pinned": false
//     },
//     {
//         "name": "Bangalore",
//         "slug": "homescreen-bangalore",
//         "geolocation": {
//             "lat": 12.971,
//             "lng": 77.594
//         },
//         "_id": "56716c6dd45525035af6984a",
//         "pinned": false
//     },
//     {
//         "name": "Bengaluru",
//         "slug": "homescreen-bengaluru",
//         "_id": "5c5d7fc51851a70007eab500",
//         "pinned": true,
//         "pinnedPosition": 2
//     },
//     {
//         "name": "Bharuch",
//         "slug": "homescreen-bharuch",
//         "_id": "5eb1bb35136e170008573a52",
//         "pinned": false
//     },
//     {
//         "name": "Bhavnagar",
//         "slug": "homescreen-bhavnagar",
//         "_id": "5c5d8d9ab41b5300078c5d9a",
//         "pinned": false
//     },
//     {
//         "name": "Bhopal",
//         "slug": "homescreen-bhopal",
//         "geolocation": {
//             "lat": 23.2599,
//             "lng": 77.4126
//         },
//         "_id": "589848b9af6bb3b3c59d4cb9",
//         "pinned": false
//     },
//     {
//         "name": "Bhubaneswar",
//         "slug": "homescreen-bhubaneswar",
//         "_id": "5c5d8d709b7c0f000721077e",
//         "pinned": false
//     },
//     {
//         "name": "Chandigarh",
//         "slug": "homescreen-chandigarh",
//         "geolocation": {
//             "lat": 30.7333,
//             "lng": 76.7794
//         },
//         "_id": "585789f4cd6aa71ac66feadd",
//         "pinned": false
//     },
//     {
//         "name": "Chennai",
//         "slug": "homescreen-chennai",
//         "geolocation": {
//             "lat": 13.0827,
//             "lng": 80.2707
//         },
//         "_id": "56724b5388349ae53898795c",
//         "pinned": true,
//         "pinnedPosition": 8
//     },
//     {
//         "name": "Coimbatore",
//         "slug": "homescreen-coimbatore",
//         "_id": "57735de2a7c8f1df431442f7",
//         "pinned": false
//     },
//     {
//         "name": "Coorg",
//         "slug": "homescreen-coorg",
//         "geolocation": {
//             "lat": 12.378391,
//             "lng": 75.2192473
//         },
//         "_id": "5b71acd64d35d8192e61e945",
//         "pinned": false
//     },
//     {
//         "name": "Dehradun",
//         "slug": "homescreen-dehradun",
//         "geolocation": {
//             "lat": 30.3253538,
//             "lng": 77.8770494
//         },
//         "_id": "5c35a83d6e0a9e62732f626c",
//         "pinned": false
//     },
//     {
//         "name": "Delhi",
//         "slug": "homescreen-delhi",
//         "geolocation": {
//             "lat": 28.613,
//             "lng": 77.209
//         },
//         "_id": "5672529b88349ae538987ba9",
//         "pinned": true,
//         "pinnedPosition": 0
//     },
//     {
//         "name": "Eluru",
//         "slug": "homescreen-eluru",
//         "_id": "5c5d8d16fc98660007b7fe15",
//         "pinned": false
//     },
//     {
//         "name": "Erode",
//         "slug": "homescreen-erode",
//         "_id": "5c5d8d6aee30470007a79291",
//         "pinned": false
//     },
//     {
//         "name": "Faridabad",
//         "slug": "homescreen-faridabad",
//         "_id": "5c5d89e6b65a6000076240a9",
//         "pinned": false
//     },
//     {
//         "name": "Gandhinagar",
//         "slug": "homescreen-gandhinagar",
//         "_id": "5c5d8d9bb41b5300078c5e0a",
//         "pinned": false
//     },
//     {
//         "name": "Ghaziabad",
//         "slug": "homescreen-ghaziabad",
//         "_id": "5c5d89e093e3a30007e7d850",
//         "pinned": false
//     },
//     {
//         "name": "Goa",
//         "slug": "homescreen-goa",
//         "geolocation": {
//             "lat": 15.2993,
//             "lng": 74.124
//         },
//         "_id": "57efa39ca7c8efc7aee74c62",
//         "pinned": true,
//         "pinnedPosition": 7
//     },
//     {
//         "name": "Gokarna",
//         "slug": "homescreen-gokarna",
//         "geolocation": {
//             "lat": 14.537,
//             "lng": 74.306
//         },
//         "_id": "614ad579b77c194ee10fac89",
//         "pinned": false
//     },
//     {
//         "name": "Greater Noida",
//         "slug": "homescreen-greater-noida",
//         "_id": "5c5d89e72aa2090007968b5d",
//         "pinned": false
//     },
//     {
//         "name": "Guntur",
//         "slug": "homescreen-guntur",
//         "_id": "5c5d8ca01641450007b5ad73",
//         "pinned": false
//     },
//     {
//         "name": "Gurgaon",
//         "slug": "homescreen-gurgaon",
//         "geolocation": {
//             "lat": 28.613,
//             "lng": 77.209
//         },
//         "_id": "5926cb72323c42f0b3612322",
//         "pinned": false
//     },
//     {
//         "name": "Gurugram",
//         "slug": "homescreen-gurugram",
//         "geolocation": {
//             "lat": 28.422,
//             "lng": 76.849
//         },
//         "_id": "61497fdeb77c194ee10fab38",
//         "pinned": false
//     },
//     {
//         "name": "Guwahati",
//         "slug": "homescreen-guwahati",
//         "_id": "586dec39cd6a8e886772c025",
//         "pinned": false
//     },
//     {
//         "name": "Haldwani",
//         "slug": "homescreen-haldwani",
//         "_id": "5c6d81f907d1530007304938",
//         "pinned": false
//     },
//     {
//         "name": "Hampi",
//         "slug": "homescreen-hampi",
//         "geolocation": {
//             "lat": 15.3331897,
//             "lng": 76.4545799
//         },
//         "_id": "5b8fb06c62b31f31643b068e",
//         "pinned": false
//     },
//     {
//         "name": "Haridwar",
//         "slug": "homescreen-haridwar",
//         "_id": "5c5d8d13b41b5300078c2b45",
//         "pinned": false
//     },
//     {
//         "name": "Hassan",
//         "slug": "homescreen-hassan",
//         "_id": "5c5d8cceee30470007a75a5d",
//         "pinned": false
//     },
//     {
//         "name": "Hospet",
//         "slug": "homescreen-hospet",
//         "_id": "5c5d8d9d2aa209000797cf01",
//         "pinned": false
//     },
//     {
//         "name": "Hosur",
//         "slug": "homescreen-hosur",
//         "_id": "5c5d8d0b9a01fa000643cdfc",
//         "pinned": false
//     },
//     {
//         "name": "Howrah",
//         "slug": "homescreen-howrah",
//         "_id": "5c5d8cc97ec11700071881ab",
//         "pinned": false
//     },
//     {
//         "name": "Hyderabad",
//         "slug": "homescreen-hyderabad",
//         "geolocation": {
//             "lat": 17.385,
//             "lng": 78.4867
//         },
//         "_id": "56724a7e88349ae53898790a",
//         "pinned": true,
//         "pinnedPosition": 5
//     },
//     {
//         "name": "Indore",
//         "slug": "homescreen-indore",
//         "geolocation": {
//             "lat": 22.7196,
//             "lng": 75.8577
//         },
//         "_id": "586debe7cd6a8e886772c021",
//         "pinned": false
//     },
//     {
//         "name": "Jaipur",
//         "slug": "homescreen-jaipur",
//         "geolocation": {
//             "lat": 26.9124,
//             "lng": 75.7873
//         },
//         "_id": "5697a87d6da291203bc5fb55",
//         "pinned": false
//     },
//     {
//         "name": "Junagadh",
//         "slug": "homescreen-junagadh",
//         "_id": "5c5d8ce67ec1170007188ad3",
//         "pinned": false
//     },
//     {
//         "name": "Karjat",
//         "slug": "homescreen-karjat",
//         "_id": "5c5d8c969a01fa0006439f6e",
//         "pinned": false
//     },
//     {
//         "name": "Karur",
//         "slug": "homescreen-karur",
//         "_id": "5ec3fb7828c6950008d18fe7",
//         "pinned": false
//     },
//     {
//         "name": "Kasol",
//         "slug": "homescreen-kasol",
//         "geolocation": {
//             "lat": 32.009,
//             "lng": 77.312
//         },
//         "_id": "61645171cc93dc41743d4497",
//         "pinned": false
//     },
//     {
//         "name": "Kochi",
//         "slug": "homescreen-kochi",
//         "geolocation": {
//             "lat": 9.9312,
//             "lng": 76.2673
//         },
//         "_id": "56ab1e8aa7c8de55a178469c",
//         "pinned": false
//     },
//     {
//         "name": "Kolar",
//         "slug": "homescreen-kolar",
//         "_id": "5ec7c3700e277f00085fe58d",
//         "pinned": false
//     },
//     {
//         "name": "Kolkata",
//         "slug": "homescreen-kolkata",
//         "geolocation": {
//             "lat": 22.5726,
//             "lng": 88.3639
//         },
//         "_id": "567249e1d45525035af6bb93",
//         "pinned": true,
//         "pinnedPosition": 4
//     },
//     {
//         "name": "Kumbakonam",
//         "slug": "homescreen-kumbakonam",
//         "_id": "5c5d8c8f9a01fa0006439cae",
//         "pinned": false
//     },
//     {
//         "name": "Lonavala",
//         "slug": "homescreen-lonavala",
//         "_id": "5c5d8c8565a6200007e2636f",
//         "pinned": false
//     },
//     {
//         "name": "Lucknow",
//         "slug": "homescreen-lucknow",
//         "geolocation": {
//             "lat": 26.8467,
//             "lng": 80.9462
//         },
//         "_id": "595c7f4cad115acf8a752403",
//         "pinned": false
//     },
//     {
//         "name": "Ludhiana",
//         "slug": "homescreen-ludhiana",
//         "geolocation": {
//             "lat": 30.901,
//             "lng": 75.8573
//         },
//         "_id": "586dfd42cd6a5928706dc2d8",
//         "pinned": false
//     },
//     {
//         "name": "Madurai",
//         "slug": "homescreen-madurai",
//         "_id": "5c5d8c6e65a6200007e25916",
//         "pinned": false
//     },
//     {
//         "name": "Mahabalipuram",
//         "slug": "homescreen-mahabalipuram",
//         "geolocation": {
//             "latitude": "12.6208",
//             "longitude": "80.1945"
//         },
//         "_id": "62e389c6306ec10009a1465c",
//         "pinned": false
//     },
//     {
//         "name": "Mangalore",
//         "slug": "homescreen-mangalore",
//         "geolocation": {
//             "lat": 12.914,
//             "lng": 74.856
//         },
//         "_id": "5b55dd557064ec01554547f9",
//         "pinned": false
//     },
//     {
//         "name": "Manipal",
//         "slug": "homescreen-manipal",
//         "_id": "5eb5ff6400d2cd0008b9619f",
//         "pinned": false
//     },
//     {
//         "name": "Meerut",
//         "slug": "homescreen-meerut",
//         "geolocation": {
//             "lat": 28.9872441,
//             "lng": 77.62892
//         },
//         "_id": "5be18fb6b4d0950cd4179ca6",
//         "pinned": false
//     },
//     {
//         "name": "Mohali",
//         "slug": "homescreen-mohali",
//         "geolocation": {
//             "lat": 30.7046,
//             "lng": 76.7179
//         },
//         "_id": "595cba5cad115acf8a752404",
//         "pinned": false
//     },
//     {
//         "name": "Morbi",
//         "slug": "homescreen-morbi",
//         "_id": "5eb3c38636afb400085506f4",
//         "pinned": false
//     },
//     {
//         "name": "Mumbai",
//         "slug": "homescreen-mumbai",
//         "geolocation": {
//             "lat": 19.08252144,
//             "lng": 72.7410965
//         },
//         "_id": "56698048d45525035af5694e",
//         "pinned": true,
//         "pinnedPosition": 1
//     },
//     {
//         "name": "Munnar",
//         "slug": "homescreen-munnar",
//         "geolocation": {
//             "lat": 10.0806491,
//             "lng": 77.0466683
//         },
//         "_id": "5afd48c5f09b4d18004e102b",
//         "pinned": false
//     },
//     {
//         "name": "Mysuru",
//         "slug": "homescreen-mysuru",
//         "geolocation": {
//             "lat": 12.3106368,
//             "lng": 76.5656493
//         },
//         "_id": "5b72de3c4d35d8192e61eac0",
//         "pinned": false
//     },
//     {
//         "name": "Nagpur",
//         "slug": "homescreen-nagpur",
//         "geolocation": {
//             "lat": 21.1458,
//             "lng": 79.0882
//         },
//         "_id": "590aed0bba7f80a7e4c771c2",
//         "pinned": false
//     },
//     {
//         "name": "Nainital",
//         "slug": "homescreen-nainital",
//         "_id": "5c5d8c78fc98660007b7c4ac",
//         "pinned": false
//     },
//     {
//         "name": "Nashik",
//         "slug": "homescreen-nashik",
//         "_id": "5a0ff02d8eede0180ea50176",
//         "pinned": false
//     },
//     {
//         "name": "Noida",
//         "slug": "homescreen-noida",
//         "geolocation": {
//             "lat": 28.5166817,
//             "lng": 77.2580446
//         },
//         "_id": "5b7d33ea4d35d8192e61ed80",
//         "pinned": false
//     },
//     {
//         "name": "Online",
//         "slug": "homescreen-online",
//         "geolocation": {
//             "lat": 0,
//             "lng": 0
//         },
//         "_id": "5e9eacd93dc0550988a466dd",
//         "pinned": true,
//         "pinnedPosition": 6
//     },
//     {
//         "name": "Ooty",
//         "slug": "homescreen-ooty",
//         "_id": "5a619159bf97a7cf6e2a75e1",
//         "pinned": false
//     },
//     {
//         "name": "Panchkula",
//         "slug": "homescreen-panchkula",
//         "_id": "5c8100f41c5a20000702e8c9",
//         "pinned": false
//     },
//     {
//         "name": "Patna",
//         "slug": "homescreen-patna",
//         "geolocation": {
//             "lat": 25.6081756,
//             "lng": 85.0730026
//         },
//         "_id": "5a95014eeec72c4cd6b02e8c",
//         "pinned": false
//     },
//     {
//         "name": "Pollachi",
//         "slug": "homescreen-pollachi",
//         "_id": "5c5d8c1a65a6200007e22bd5",
//         "pinned": false
//     },
//     {
//         "name": "Puducherry",
//         "slug": "homescreen-puducherry",
//         "geolocation": {
//             "lat": 11.9416,
//             "lng": 79.8083
//         },
//         "_id": "59b10c77c7b9d42934f28be9",
//         "pinned": false
//     },
//     {
//         "name": "Pune",
//         "slug": "homescreen-pune",
//         "geolocation": {
//             "lat": 18.52,
//             "lng": 73.856
//         },
//         "_id": "56717609d45525035af69bf5",
//         "pinned": true,
//         "pinnedPosition": 3
//     },
//     {
//         "name": "Rajahmundry",
//         "slug": "homescreen-rajahmundry",
//         "_id": "5c5d8bea2aa2090007972860",
//         "pinned": false
//     },
//     {
//         "name": "Ranchi",
//         "slug": "homescreen-ranchi",
//         "geolocation": {
//             "lat": 23.3441,
//             "lng": 85.3096
//         },
//         "_id": "586dec08cd6a8e886772c023",
//         "pinned": false
//     },
//     {
//         "name": "Rishikesh",
//         "slug": "homescreen-rishikesh",
//         "_id": "5c3d7f836a7c631e42d14ac8",
//         "pinned": false
//     },
//     {
//         "name": "Rourkela",
//         "slug": "homescreen-rourkela",
//         "_id": "5ed19c24f2d7a00008c3b3e7",
//         "pinned": false
//     },
//     {
//         "name": "Satara",
//         "slug": "homescreen-satara",
//         "geolocation": {
//             "longitude": "0",
//             "latitude": "0"
//         },
//         "_id": "67a9dac614406cbee4d61aff",
//         "pinned": false
//     },
//     {
//         "name": "Secunderabad",
//         "slug": "homescreen-secunderabad",
//         "geolocation": {
//             "lat": 17.5370297,
//             "lng": 78.4312759
//         },
//         "_id": "5bf649a508fc690515c99efb",
//         "pinned": false
//     },
//     {
//         "name": "Shillong",
//         "slug": "homescreen-shillong",
//         "geolocation": {
//             "lat": 25.5901143,
//             "lng": 91.8223968
//         },
//         "_id": "5c14b0e83929f695f88c8642",
//         "pinned": false
//     },
//     {
//         "name": "Shivamogga",
//         "slug": "homescreen-shivamogga",
//         "_id": "5d847672903c5e0009b33984",
//         "pinned": false
//     },
//     {
//         "name": "Solan",
//         "slug": "homescreen-solan",
//         "_id": "5c5d8bffee30470007a6f6ff",
//         "pinned": false
//     },
//     {
//         "name": "Surat",
//         "slug": "homescreen-surat",
//         "geolocation": {
//             "lat": 21.1702,
//             "lng": 72.8311
//         },
//         "_id": "5890553faf7d2f3277d6c3e4",
//         "pinned": false
//     },
//     {
//         "name": "Surendranagar",
//         "slug": "homescreen-surendranagar",
//         "_id": "5c5d8bd865a6200007e2012b",
//         "pinned": false
//     },
//     {
//         "name": "Tadepalligudem",
//         "slug": "homescreen-tadepalligudem",
//         "_id": "5c5d8ba02aa209000796f8a8",
//         "pinned": false
//     },
//     {
//         "name": "Thane",
//         "slug": "homescreen-thane",
//         "geolocation": {
//             "lat": 19.213,
//             "lng": 72.931
//         },
//         "_id": "5c5d8afd2aa20900079699d1",
//         "pinned": false
//     },
//     {
//         "name": "Thiruvananthapuram",
//         "slug": "homescreen-thiruvananthapuram",
//         "geolocation": {
//             "lat": 8.5241391,
//             "lng": 76.9366376
//         },
//         "_id": "5bc5d2596c1e22011bfda6f3",
//         "pinned": false
//     },
//     {
//         "name": "Thrissur",
//         "slug": "homescreen-thrissur",
//         "geolocation": {
//             "lat": 10.5276,
//             "lng": 76.2144
//         },
//         "_id": "59f83b342d35dc5304a2217a",
//         "pinned": false
//     },
//     {
//         "name": "Tirunelveli",
//         "slug": "homescreen-tirunelveli",
//         "geolocation": {
//             "lat": 8.7139,
//             "lng": 77.7567
//         },
//         "_id": "5b447358c780fb014c6ef51c",
//         "pinned": false
//     },
//     {
//         "name": "Tirupati",
//         "slug": "homescreen-tirupati",
//         "geolocation": {
//             "longitude": "13.6287557",
//             "latitude": "79.4191795"
//         },
//         "_id": "5dcd223ab760dd000880c681",
//         "pinned": false
//     },
//     {
//         "name": "Tirupur",
//         "slug": "homescreen-tirupur",
//         "_id": "5c5d8ba5ee30470007a6c3af",
//         "pinned": false
//     },
//     {
//         "name": "Trichy",
//         "slug": "homescreen-trichy",
//         "_id": "5c5d8bd37ec11700071814de",
//         "pinned": false
//     },
//     {
//         "name": "Trivandrum",
//         "slug": "homescreen-trivandrum",
//         "_id": "59c104c7fc4e95d08e947d18",
//         "pinned": false
//     },
//     {
//         "name": "Udaipur",
//         "slug": "homescreen-udaipur",
//         "geolocation": {
//             "lat": 24.60827,
//             "lng": 73.6370181
//         },
//         "_id": "5b86578762b31f31643afdfd",
//         "pinned": false
//     },
//     {
//         "name": "Vadodara",
//         "slug": "homescreen-vadodara",
//         "geolocation": {
//             "lat": 22.3072,
//             "lng": 73.1812
//         },
//         "_id": "5698d78fd393d291630ca675",
//         "pinned": false
//     },
//     {
//         "name": "Varanasi",
//         "slug": "homescreen-varanasi",
//         "geolocation": {
//             "lat": 25.3176,
//             "lng": 82.9739
//         },
//         "_id": "5a9fa63feec72c73fc67974d",
//         "pinned": false
//     },
//     {
//         "name": "Vijayawada",
//         "slug": "homescreen-vijayawada",
//         "_id": "5c5d8b87bd7c1e00072f5355",
//         "pinned": false
//     },
//     {
//         "name": "Visakhapatnam",
//         "slug": "homescreen-visakhapatnam",
//         "geolocation": {
//             "longitude": "83.2184815",
//             "latitude": "17.6868159"
//         },
//         "_id": "5dea04d788352f000851cbf0",
//         "pinned": false
//     },
//     {
//         "name": "Vizag",
//         "slug": "homescreen-vizag",
//         "geolocation": {
//             "lat": 17.6868,
//             "lng": 83.2185
//         },
//         "_id": "59a3d0adc7b9d4b51e955c2d",
//         "pinned": false
//     },
//     {
//         "name": "Vizianagaram",
//         "slug": "homescreen-vizianagaram",
//         "_id": "5c5d8b872aa209000796e22b",
//         "pinned": false
//     },
//     {
//         "name": "Warangal",
//         "slug": "homescreen-warangal",
//         "_id": "5c5d8b862aa209000796dff2",
//         "pinned": false
//     },
//     {
//         "name": "Wayanad",
//         "slug": "homescreen-wayanad",
//         "_id": "5c5d8b7b2aa209000796d5f9",
//         "pinned": false
//     }
// ]

const eventCategories = {
    "Concerts & Music": [
        "Concert", "Music Festival", "Live DJ Set", "Classical Music Performance", "Open Mic Night", "Battle of the Bands"
    ],
    "Sports & Fitness": [
        "Football Match", "Basketball Game", "Marathon", "Yoga Class", "Gym Training Session", "Swimming Competition"
    ],
    "Conferences & Business": [
        "Tech Conference", "Business Summit", "Networking Event", "Startup Pitch Competition", "Workshop", "Career Fair"
    ],
    "Education & Learning": [
        "Seminar", "Webinar", "Coding Bootcamp", "Science Fair", "Art Workshop", "Book Reading"
    ],
    "Entertainment & Arts": [
        "Movie Premiere", "Theatre Play", "Stand-up Comedy", "Magic Show", "Art Exhibition", "Dance Performance"
    ],
    "Festivals & Cultural": [
        "Food Festival", "Film Festival", "Traditional Festival", "Carnival", "Religious Gathering", "Independence Day Celebration"
    ],
    "Technology & Innovation": [
        "Hackathon", "AI Summit", "Robotics Expo", "Cybersecurity Conference", "Software Developer Meetup", "Gaming Convention"
    ],
    "Health & Wellness": [
        "Mental Health Seminar", "Nutrition Workshop", "Meditation Retreat", "Blood Donation Camp", "First Aid Training"
    ],
    "Outdoor & Adventure": [
        "Hiking Trip", "Camping Event", "Skydiving Session", "Scuba Diving Training", "Wildlife Safari", "Cycling Race"
    ],
    "Social & Community": [
        "Charity Event", "Fundraiser", "Volunteer Drive", "Town Hall Meeting", "Public Debate", "Protest"
    ],
    "Nightlife & Parties": [
        "Club Party", "Cocktail Night", "Themed Costume Party", "VIP Gala", "Rave Party"
    ],
    "Gaming & eSports": [
        "eSports Tournament", "LAN Party", "Board Game Night", "VR Gaming Experience", "Poker Night"
    ],
    "Family & Kids": [
        "Puppet Show", "Kids Science Camp", "Storytelling Event", "Baby Shower", "Parent-Teacher Meeting"
    ],
    "Science & Space": [
        "Astronomy Night", "Science Exhibition", "Space Exploration Talk", "Drone Show", "NASA Event"
    ],
    "Spiritual & Religious": [
        "Church Service", "Meditation Camp", "Pilgrimage", "Religious Festival", "Healing Session"
    ]
};
const findClosestCity = (city) => {
    var citywords = city.split(" ");
    var citywords = citywords.filter(word => word.length > 2); // Filter out words with length <= 2
    for (var i = 0; i < citywords.length; i++) {
        citywords[i] = citywords[i].replace(/[^a-zA-Z]/g, ""); // Remove special characters
        citywords[i] = citywords[i].replace(/_/g, " "); // Replace underscores with spaces
        citywords[i] = citywords[i].replace(/-/g, " "); // Replace hyphens with spaces
        citywords[i] = citywords[i].replace(/\s+/g, " "); // Replace multiple spaces with a single space
        citywords[i] = citywords[i].replace(/,/g, " "); // Replace commas with spaces

        citywords[i] = citywords[i].charAt(0).toUpperCase() + citywords[i].slice(1);
        citywords[i] = citywords[i].trim(); // Trim leading and trailing spaces
        // console.log("Finding closest city for:", citywords[i]);
        const fuse = new Fuse(indianCities, { threshold: 0.1 });

        const result = fuse.search(citywords[i]);
        // console.log("Search result:", result);
        if (result.length > 0) {
            // console.log("Search result:", result);
            return result.length > 0 ? result[0].item : "Unknown City";
        }

    }
    return city;


};
function LocationBlock({ fetchEvents }) {
    const [location, setLocation] = useState("Fetching location...");
    const [customLocation, setCustomLocation] = useState("");
    const [suggestions, setSuggestions] = useState([]);

    useEffect(() => {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                (position) => {
                    fetch(
                        `https://nominatim.openstreetmap.org/reverse?lat=${position.coords.latitude}&lon=${position.coords.longitude}&format=json`
                    )
                        .then((res) => res.json())
                        .then((data) => {
                            // console.log(data);
                            if (!data || !data.address) {
                                setLocation("Location unavailable");
                                return;
                            }
                            const city = data.address.state_district || data.address.state || data.address.county || "Unknown City";
                            // console.log(city);

                            const matchedCity = findClosestCity(city);
                            setLocation(matchedCity);
                            if (matchedCity !== location) {
                                fetchEvents(matchedCity);
                            }
                        })
                        .catch(() => setLocation("Location unavailable"));
                },
                () => {
                    setLocation("Location permission denied")
                }
            );
        } else {
            setLocation("Geolocation not supported");
        }
    }, []);

    const fetchLocations = (query) => {
        if (query.length > 2) {
            const filteredCities = indianCities.filter(city => city.toLowerCase().includes(query.toLowerCase()));
            setSuggestions(filteredCities);
        } else {
            setSuggestions([]);
        }
    };

    return (
        <div className="d-flex flex-column align-items-end gap-2">
            <div className="d-flex align-items-center gap-2">
                <FontAwesomeIcon icon={faMapMarkerAlt} className="text-primary" />
                <span className="text-muted">{location}</span>
            </div>
            <div className="position-relative">
                <input
                    type="text"
                    className="form-control"
                    placeholder="Enter location"
                    value={customLocation}
                    onChange={(e) => {
                        setCustomLocation(e.target.value);
                        fetchLocations(e.target.value);
                    }}
                />
                {suggestions.length > 0 && (
                    <ul className="list-group position-absolute w-100 mt-1" style={{ zIndex: 10 }}>
                        {suggestions.map((city, index) => (
                            <li
                                key={index}
                                className="list-group-item list-group-item-action"
                                onClick={() => {
                                    setLocation(city);
                                    fetchEvents(city);
                                    setCustomLocation("");
                                    setSuggestions([]);
                                }}
                            >
                                {city}
                            </li>
                        ))}
                    </ul>
                )}
            </div>
        </div>
    );
}
const FestivalsEvents = () => {
    const [visibleCount, setVisibleCount] = useState(12);
    const [selectedFilter, setSelectedFilter] = useState(null);
    const [currentLocation, setCurrentLocation] = useState(null);
    const [events, setEvents] = useState([]);

    const fetchEvents = async (city) => {
        // const encodedCity = encodeURIComponent(city);
        const res = await fetch(
            `${process.env.REACT_APP_BACKEND_BASE_URL}/api/events/getEventsForLocation`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ locationName: city.split("-")[0], locationCode: "" }),
            }
        );
        const data = await res.json();
        // console.log("Events data:", data.events);

        setEvents(data.events || []);
    };
    const handleLocationChange = (city) => {
        setCurrentLocation(city);
        // Only fetch events once, not multiple times
        fetchEvents(city);
    };

    const handleFilterChange = (category) => {
        setSelectedFilter(category);
        if (currentLocation) {
            fetchEvents(currentLocation);  // Only call if currentLocation is set
        }
    };

    const handleShowMore = () => {
        setVisibleCount(locations.length); // Show all locations
    };



    return (
        <section className="">
            <div className='row'>
                <div className='col-lg-8 col-sm-12 col-md-8'>
                    <h2 className="fw-bold majorHeadings" style={{ textAlign: "left" }}>Festivals & Events</h2>
                    {/* Filters */}
                    {/* <div className="mt-3">
                        {Object.keys(eventCategories).map((category) => (
                            <button
                                key={category}
                                className={`btn ${selectedFilter === category ? 'btn-primary' : 'btn-outline-primary'} me-2 mb-2`}
                                onClick={() => handleFilterChange(category)}
                            >
                                {category}
                            </button>
                        ))}
                    </div> */}
                </div>
                <div className='col-lg-4 col-sm-12 col-md-4'>
                    <LocationBlock fetchEvents={fetchEvents} />
                </div>
            </div>

            {/* Display Events or Locations */}
            <div className='col-lg-12'
                style={{
                    display: "flex",
                    justifyContent: "space-around",
                    flexWrap: "wrap"
                }}
            >

                {events.length > 0 ? (
                    <EventList events={events.slice(0, visibleCount)} />
                ) : (
                    <EmptyState />
                )}
            </div>

            {visibleCount < locations.length && events.length > 0 && (
                <div style={{ textAlign: 'center', margin: '20px 0' }}>
                    <button className="btn btn-black" onClick={handleShowMore}>
                        Show More
                    </button>
                </div>
            )}
        </section>
    );
};
export default FestivalsEvents;